param(
    [string]$MainModPath = 'E:\SteamLibrary\steamapps\workshop\content\1158310\2962713441',
    [string]$TranslationPath = 'E:\SteamLibrary\steamapps\workshop\content\1158310\3736917258',
    [switch]$Check
)
. (Join-Path $PSScriptRoot '../../../tools/RepositoryText.ps1')


$ErrorActionPreference = 'Stop'
$modRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$utf8 = [Text.UTF8Encoding]::new($true, $true)
$entryPattern = [regex]'^\s*(?<key>[^\s#":]+):\s*(?:\d+\s*)?"(?<text>.*)"\s*(?:#.*)?$'
$baseline = Get-Content -LiteralPath (Join-Path $modRoot 'docs/source-baseline.json') -Raw -Encoding UTF8 | ConvertFrom-Json
$corrections = Get-Content -LiteralPath (Join-Path $modRoot 'docs/corrections.json') -Raw -Encoding UTF8 | ConvertFrom-Json

function Replace-Once([string]$Text, [string]$Before, [string]$After) {
    if ([regex]::Matches($Text, [regex]::Escape($Before)).Count -ne 1) { throw "Expected exactly one source fragment: $Before" }
    return $Text.Replace($Before, $After)
}

function Read-Catalog([string]$Text, [string]$Language, [switch]$Structure) {
    $entries = [Collections.Generic.Dictionary[string,string]]::new([StringComparer]::Ordinal)
    $headers = 0
    foreach ($line in $Text.TrimStart([char]0xFEFF) -split '\r?\n') {
        if ($line -match '^\s*(?:#.*)?$') { continue }
        if ($line -cmatch ('^l_' + $Language + ':\s*$')) { $headers++; continue }
        $match = $entryPattern.Match($line)
        if (-not $match.Success) { throw "Malformed localization: $line" }
        $value = $match.Groups['text'].Value
        if ($Structure) {
            if ([regex]::Matches($value,'\[').Count -ne [regex]::Matches($value,'\]').Count -or
                [regex]::Matches($value,'\$').Count % 2 -ne 0 -or $value -match '\\(?![nrt"\\])') { throw 'Broken localization template.' }
            $depth = 0
            foreach ($token in [regex]::Matches($value, '#!|#[A-Za-z][A-Za-z0-9_]*')) {
                if ($token.Value -eq '#!') { $depth-- } else { $depth++ }
                if ($depth -lt 0) { throw 'Unexpected formatting close.' }
            }
            if ($depth -ne 0) { throw 'Unclosed formatting.' }
        }
        $entries.Add($match.Groups['key'].Value, $value)
    }
    if ($headers -ne 1) { throw "Expected one $Language header." }
    return ,$entries
}

# Verify all audited EN/RU sources plus the script before generating any files.
if ($baseline.Sources.Count -ne 19) { throw 'Expected 18 localization sources and one memory script.' }
foreach ($source in $baseline.Sources) {
    $root = if ($source.Catalog -eq 'Translation') { $TranslationPath } else { $MainModPath }
    $path = Join-Path $root $source.File
    if ((Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash -cne $source.SHA256) { throw "Source changed; repeat the audit: $path" }
}

$patch = [Collections.Generic.Dictionary[string,string]]::new([StringComparer]::Ordinal)
$changes = @()
foreach ($correction in $corrections) {
    $source = Read-Catalog ([IO.File]::ReadAllText((Join-Path $TranslationPath $correction.File), $utf8)) 'russian' -Structure
    if (-not $source.ContainsKey($correction.Key)) { throw "Missing source key: $($correction.Key)" }
    $before = $source[$correction.Key]
    $after = Replace-Once $before $correction.Before $correction.After
    $patch.Add($correction.Key, $after)
    $changes += [pscustomobject]@{ Issue=$correction.Issue; File=$correction.File; Key=$correction.Key; Before=$before; After=$after }
}
if ($patch.Count -ne 6) { throw 'Expected six Russian localization changes.' }

$memoryFile = 'common/character_memory_types/valyrian_memories.txt'
$memoryBefore = [IO.File]::ReadAllText((Join-Path $MainModPath $memoryFile), $utf8)
$memoryAfter = Replace-Once $memoryBefore 'desc = hurt_someone_close_to_me_desc_third_perspective' 'desc = hurt_exploring_valyria_desc_third_perspective'
$englishFile = 'localization/english/valyrian_decisions_l_english.yml'
$englishBefore = [IO.File]::ReadAllText((Join-Path $MainModPath $englishFile), $utf8)
$broken = [regex]::Matches($englishBefore, '(?m)^fund_expedition_0012_desc:[^\r\n]*')
if ($broken.Count -ne 1 -or $broken[0].Value.EndsWith('"')) { throw 'Expected one unterminated English description.' }
$englishAfter = Replace-Once $englishBefore $broken[0].Value ($broken[0].Value + '"')

$overlayFile = 'localization/replace/russian/zzzz_valyrian_steel_rus_correct_l_russian.yml'
$overlay = @('l_russian:', ' # Generated by tools/Build-ValyrianSteelRusCorrect.ps1; six confirmed localization fixes only.')
foreach ($key in $patch.Keys | Sort-Object -CaseSensitive) { $overlay += ' ' + $key + ':0 "' + $patch[$key] + '"' }
$outputs = [ordered]@{}
$outputs[$overlayFile] = ($overlay -join "`n") + "`n"
$outputs[$memoryFile] = $memoryAfter
$outputs[$englishFile] = $englishAfter

# Read the complete effective catalogs, using the repaired English file.
$en = [Collections.Generic.Dictionary[string,string]]::new([StringComparer]::Ordinal)
$ru = [Collections.Generic.Dictionary[string,string]]::new([StringComparer]::Ordinal)
foreach ($source in $baseline.Sources) {
    if ($source.Catalog -notin @('EN','Translation')) { continue }
    $isEnglish = $source.Catalog -eq 'EN'
    $root = if ($isEnglish) { $MainModPath } else { $TranslationPath }
    $content = if ($isEnglish -and $source.File -eq $englishFile) { $englishAfter } else { [IO.File]::ReadAllText((Join-Path $root $source.File), $utf8) }
    $catalog = Read-Catalog $content $(if ($isEnglish) { 'english' } else { 'russian' }) -Structure
    $target = if ($isEnglish) { $en } else { $ru }
    foreach ($key in $catalog.Keys) { $target.Add($key, $catalog[$key]) }
}
if ($en.Count -ne 286 -or $ru.Count -ne 286) { throw 'Expected complete 286-key catalogs.' }
foreach ($key in $en.Keys) { if (-not $ru.ContainsKey($key)) { throw "Missing Russian key: $key" } }
$overlayCatalog = Read-Catalog $outputs[$overlayFile] 'russian' -Structure
foreach ($key in $overlayCatalog.Keys) { $ru[$key] = $overlayCatalog[$key] }

# Validate the localization contract of each memory against its participants.
# This catches the missing adventurer and the unrelated close_relation reference.
$memoryBlocks = [regex]::Matches($memoryAfter, '(?ms)^(?<key>[A-Za-z_][A-Za-z_0-9]*)\s*=\s*\{.*?(?=^[A-Za-z_][A-Za-z_0-9]*\s*=\s*\{|\z)')
if ($memoryBlocks.Count -ne 8) { throw 'Unexpected number of memory types.' }
foreach ($block in $memoryBlocks) {
    $allowed = [Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
    [void]$allowed.Add('owner')
    $participants = [regex]::Match($block.Value, 'participants\s*=\s*\{(?<names>[^}]*)\}')
    foreach ($name in [regex]::Matches($participants.Groups['names'].Value, '[A-Za-z_]+')) { [void]$allowed.Add($name.Value) }
    foreach ($desc in [regex]::Matches($block.Value, '\bdesc\s*=\s*(?<key>[A-Za-z_0-9]+)')) {
        $key = $desc.Groups['key'].Value
        if (-not $ru.ContainsKey($key)) { throw "Memory has no local Russian description: $key" }
        foreach ($expression in [regex]::Matches($ru[$key], '\[[^\]]*\]')) {
            foreach ($scope in [regex]::Matches($expression.Value, '\b(?<scope>[a-z][A-Za-z_0-9]*)\.')) {
                if (-not $allowed.Contains($scope.Groups['scope'].Value)) { throw "Unavailable scope in ${key}: $($scope.Groups['scope'].Value)" }
            }
        }
    }
}

# Render both grammatical branches in the four corrected ruler sentences.
$genderKeys = @('fund_expedition_0001_desc','fund_expedition_00021_desc','fund_expedition_0014_desc','fund_expedition_0014_alt_desc')
$expectedFemale = @('я готова снарядить','Я велела искать','которого я ждала','которого я ждала')
$expectedMale = @('я готов снарядить','Я велел искать','которого я ждал','которого я ждал')
$genderPattern = [regex]"\[Select_CString\(ROOT\.Char\.IsFemale, '([^']+)', '([^']+)'\)\]"
for ($i=0; $i -lt $genderKeys.Count; $i++) {
    $value = $ru[$genderKeys[$i]]
    if ($genderPattern.Matches($value).Count -ne 1 -or
        -not $genderPattern.Replace($value, '$1').Contains($expectedFemale[$i]) -or
        -not $genderPattern.Replace($value, '$2').Contains($expectedMale[$i])) { throw 'Incorrect ruler gender branches.' }
}

$descriptor = @(
    'version="1.0.0"', 'tags={', '    "Translation"', '    "Fixes"', '}',
    ('name="' + $baseline.ModName + '"'), 'supported_version="1.19.0.6"',
    'dependencies={', '    "Valyrian Steel"', ('    "Valyrian Steel - ' + $baseline.TranslationNameSuffix + '"'), '}'
) -join "`n"
$outputs['descriptor.mod'] = $descriptor + "`n"
$externalDescriptor = $descriptor + "`npath=""" + $modRoot.Replace('\','/') + """`n"
$externalPath = Join-Path (Split-Path -Parent $modRoot) 'VALYRIAN_STEEL_RUS_CORRECT.mod'
foreach ($line in $externalDescriptor -split '\r?\n') {
    if ([regex]::Matches($line, '"').Count % 2 -ne 0) { throw 'Multiline or unterminated descriptor string.' }
}
if ($externalDescriptor -notmatch '(?m)^path="([^"\r\n]+)"$' -or
    [IO.Path]::GetFullPath($Matches[1]) -ne $modRoot) { throw 'External descriptor does not point to this mod.' }

function Write-Or-Check([string]$Path, [string]$Content) {
    $Content=[RepositoryText]::Normalize($Content)
    if ($Check) {
        $expectedBytes = $utf8.GetPreamble() + $utf8.GetBytes($Content)
        if (-not (Test-Path -LiteralPath $Path) -or
            [Convert]::ToBase64String([IO.File]::ReadAllBytes($Path)) -cne [Convert]::ToBase64String($expectedBytes)) { throw "Package differs from reviewed corrections: $Path" }
    } else {
        [IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($Path)) | Out-Null
        [RepositoryText]::WriteAllText($Path, $Content, $utf8)
    }
}

$manifestOutputs = @()
foreach ($file in $outputs.Keys) {
    $path = Join-Path $modRoot $file
    Write-Or-Check $path $outputs[$file]
    $manifestOutputs += [pscustomobject]@{ File=$file; SHA256=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash }
}
Write-Or-Check $externalPath $externalDescriptor
$manifest = [ordered]@{
    MainWorkshopId='2962713441'; MainVersion='1.4.1'; TranslationWorkshopId='3736917258'; TranslationVersion='1.4.1-ru'
    ConfirmedIssues=@('VS-001','VS-002','VS-003','VS-004','VS-005','VS-006','VS-007')
    RussianChanges=$changes
    MemoryScript=[ordered]@{ File=$memoryFile; Before='desc = hurt_someone_close_to_me_desc_third_perspective'; After='desc = hurt_exploring_valyria_desc_third_perspective' }
    EnglishSyntax=[ordered]@{ File=$englishFile; Key='fund_expedition_0012_desc'; Before=$broken[0].Value; After=($broken[0].Value+'"') }
    Outputs=$manifestOutputs; ExternalDescriptorSHA256=(Get-FileHash -LiteralPath $externalPath -Algorithm SHA256).Hash
}
Write-Or-Check (Join-Path $modRoot 'docs/source-manifest.json') (($manifest | ConvertTo-Json -Depth 8) + "`n")

if ($Check) {
    $actualFiles = @(Get-ChildItem -LiteralPath (Join-Path $modRoot 'localization'),(Join-Path $modRoot 'common') -File -Recurse)
    if ($actualFiles.Count -ne 3) { throw 'Unexpected game files in the correction mod.' }
}
Write-Output 'Validated: 286 effective Russian keys; 6 exact localization changes; 8 memory types and their scopes; female/male ruler forms; 1 English closing quote; 19 unchanged source hashes.'
Write-Output $(if ($Check) { 'Package matches reviewed changes byte for byte. Editorial wording is preserved.' } else { 'Built VALYRIAN_STEEL_RUS_CORRECT and its external .mod descriptor.' })
